name: "Deploy Docker to Caprover"

description: "An Action to build a docker image and deploy to Caprover."
author: "Alexandru Boscan"

branding:
  icon: upload-cloud
  color: gray-dark
inputs:
  auth_used:
    description: "Authentication method: password or token"
    required: true
  url:
    description: "CapRover server URL"
    required: true
  app:
    description: "CapRover app name"
    required: true
  email:
    description: "Email for CapRover login (if using password auth)"
    required: false
  password:
    description: "Password for CapRover login (if using password auth)"
    required: false
  app_token:
    description: "App token for CapRover deploy (if using token auth)"
    required: false
  branch:
    description: "GitHub branch to deploy"
    required: true
  token:
    description: "GitHub token to access the container registry"
    required: true
  docker_image:
    description: "Docker image name"
    required: true
  dockerfile_path:
    description: "Path to the Dockerfile"
    required: true

runs:
  using: composite
  steps:
    - run: |
        export REPO=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
        export REGISTRY_USER=${{ github.actor }}
        export REGISTRY_PASSWORD=${{inputs.token}}
        export REGISTRY_URL="ghcr.io"
        export COMMIT_HASH=$GITHUB_SHA
        export IMAGE_NAME_WITH_REGISTRY_PREFIX=$REGISTRY_URL/$REPO
        echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin $REGISTRY_URL
        echo "Building..."
        export CONTAINER_FULL_IMAGE_NAME_WITH_TAG=$IMAGE_NAME_WITH_REGISTRY_PREFIX:$COMMIT_HASH
        docker build -t "${{ inputs.docker_image }}" --dockerfile "${{ inputs.dockerfile_path }}" .
        docker tag "${{ inputs.docker_image }}" "$CONTAINER_FULL_IMAGE_NAME_WITH_TAG"
        docker push "$CONTAINER_FULL_IMAGE_NAME_WITH_TAG"
        echo $CONTAINER_FULL_IMAGE_NAME_WITH_TAG
        echo "Deploying on CapRover..."
        docker run caprover/cli-caprover:2.2.3 caprover deploy -u ${{inputs.url}} -p ${{inputs.password}} -a ${{inputs.app}} -i $CONTAINER_FULL_IMAGE_NAME_WITH_TAG
      shell: bash
